version: "3.7"
services:
  open_redirect:
    container_name: open_redirect
    build:
      context: OpenRedirect
    ports:
      - 8081:80
    volumes:
      - ./OpenRedirect/app:/app

  html_injection:
    container_name: html_injection
    build:
      context: HtmlInjection
    ports:
      - 8082:80
    volumes:
      - ./HtmlInjection/app:/app

  security_misconfig:
    container_name: security_misconfig
    build:
      context: SecurityMisconfig
    ports:
      - 8083:80
    volumes:
      - ./SecurityMisconfig/app:/app

  lfi:
    container_name: lfi
    build:
      context: LFI
    ports:
      - 8084:80
    volumes:
      - ./LFI/app:/app

  ssrf:
    container_name: ssrf
    build:
      context: SSRF
    ports:
      - 8085:80
    volumes:
      - ./SSRF/app:/app

  file_server:
    container_name: file_server
    image: